### ISSUE TITLE
Handle multiple clozes with the same number, e.g. two different `{{c2::*}}`s

### ISSUE THREAD

**Issue by michalrus** [michalrus/anki-simple-cloze-overlapper#4]
@gianDgiant wrote on _2023-02-25T11:44:00Z_ in the [original Gist](https://gist.github.com/michalrus/fe16637f6bdc329ba35f635a4b4994bc):

> @michalrus First of all, thank you so much for making this.
> 
> Can you make it possible for a card like this to be generated properly?
> 
> {{c1::Simple Squamous Epithelium}} is described to have:
> - {{c2::single}} layer of {{c2::flattened}} cells
> - {{c3::disc}} shaped {{c3::central}} nuclei
> - {{c4::sparse}} cytoplasm
> {{c99::ask-all}}
> 
> If I were to generate that with the latest version, it skips the first c2 and c3 words. Thank you.

**Comment by michalrus** [comment]
@gianDgiant that looks useful, let me try! ⌛

**Comment by michalrus** [comment]
I think it should be solved now in 0dcb0a4ed2f6870a25cb3d46b9c635fe70f5e946.

@gianDgiant, can you check it out and let me know? Feel free to reopen if something is wrong

![issue-4](https://user-images.githubusercontent.com/4366292/221376167-22e80506-7cd1-490b-b82e-7377dd7aced2.gif)

**Comment by gianDgiant** [comment]
It works just as I wanted. Thank you so much!

**Comment by gianDgiant** [comment]
@michalrus The note won't generate cards properly if the clozes with the same number also have the same words. Try making a card with this to see.

blah blah blah
{{c1::A}} to {{c1::B}}
{{c2::B}} to {{c2::B}}
{{c3::B}} to {{c3::C}}

**Comment by michalrus** [comment]
@gianDgiant OK, it's more resilient now, thanks! =) 

Should be fixed in 7e1eb9463ae8454c34790059261d4863ab2a1b7c:

![issue-4-2](https://user-images.githubusercontent.com/4366292/221405649-09b41f69-ea49-4a2c-ae13-109922e255ab.gif)
